name: Skeptical Snake
source: https://www.reddit.com/r/JoeRogan/comments/5kga5k/skeptical_snake/
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    start: 0.0
    stop: 1.0
example:
  - when you already checked that one leaf
  - and it starts moving
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
