name: Kombucha Girl
source: https://www.buzzfeed.com/daniellaemanuel/woman-trying-kombucha-meme
text:
  - style: default
    color: black
    font: thick
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 0.5
    scale_y: 0.3
    start: 0.2
    stop: 1.0
  - style: default
    color: black
    font: thick
    anchor_x: 0.5125
    anchor_y: 0.0
    angle: 0.0
    scale_x: 0.4875
    scale_y: 0.3
    start: 0.6
    stop: 1.0
example:
  - Trying a thing.
  - Trying a thing again.
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
