name: Galaxy Brain
source: https://knowyourmeme.com/memes/galaxy-brain
text:
  - style: none
    color: black
    font: thin
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 0.49
    scale_y: 0.245
  - style: none
    color: black
    font: thin
    anchor_x: 0.0
    anchor_y: 0.255
    angle: 0.0
    scale_x: 0.49
    scale_y: 0.246
  - style: none
    color: black
    font: thin
    anchor_x: 0.0
    anchor_y: 0.51
    angle: 0.0
    scale_x: 0.489
    scale_y: 0.224
  - style: none
    color: black
    font: thin
    anchor_x: 0.0
    anchor_y: 0.746
    angle: 0.0
    scale_x: 0.49
    scale_y: 0.255
styles:
  -
example:
  - Who
  - Whom
  - Whom'st
  - Whomst'd
overlay:
  - center_x: 0.5
    center_y: 0.5
    scale: 0.25
