name: Probably Not a Good Idea
source: https://www.youtube.com/watch?v=RFinNxS5KN4&t=86
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
  - style: upper
    color: white
    font: thick
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
example:
  - you just went and made a new dinosaur?
  - probably not a good idea
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
