language: python
python:
  - 3.6

cache:
  pip: true
  directories:
    - .venv

env:
  global:
    - RANDOM_SEED=0
    - PIPENV_NOSPIN=true
    - REGENERATE_IMAGES=true
    - VALIDATE_LINKS=true

before_install:
  - pip install pipenv==5.3.5
  - make doctor

install:
  - make install

script:
  - make check
  - make test
  - make validate

after_success:
  - pip install coveralls scrutinizer-ocular
  - coveralls
  - ocular

notifications:
  email:
    on_success: never
    on_failure: never
