name: Disappointed Black Guy / Expectation vs. Reality
source: https://knowyourmeme.com/memes/disappointed-black-guy
text:
  - style: default
    color: black
    font: thin
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 0.48
    scale_y: 0.5
    start: 0.0
    stop: 1.0
  - style: default
    color: black
    font: thin
    anchor_x: 0.0
    anchor_y: 0.5
    angle: 0.0
    scale_x: 0.48
    scale_y: 0.5
    start: 0.0
    stop: 1.0
example:
  - Clicking the 'X' on a mobile ad
  - The 'X' is part of the ad
overlay:
  - center_x: 0.25
    center_y: 0.245
    angle: 0.0
    scale: 0.492
  - center_x: 0.25
    center_y: 0.75
    angle: 0.0
    scale: 0.5
