name: Hipster Barista
source: http://knowyourmeme.com/memes/hipster-barista
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    start: 0.0
    stop: 1.0
example:
  - ''
  - ''
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
