name: Grant Gustin Next To Oliver Queen's Grave
source: https://knowyourmeme.com/memes/grant-gustin-next-to-oliver-queens-grave
text:
  - style: upper
    color: silver
    font: thick
    anchor_x: 0.14
    anchor_y: 0.23
    angle: 4.0
    scale_x: 0.2
    scale_y: 0.23
    align: center
    start: 0.0
    stop: 1.0
  - style: default
    color: white
    font: thin
    anchor_x: 0.1
    anchor_y: 0.75
    angle: 5.0
    scale_x: 0.4
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: default
    color: white
    font: thin
    anchor_x: 0.5
    anchor_y: 0.48
    angle: 20.0
    scale_x: 0.4
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - Here lies the last bit of human decency
  - Society
  - Social Media
overlay:
  - center_x: 0.245
    center_y: 0.35
    angle: 4.0
    scale: 0.22
  - center_x: 0.29
    center_y: 0.85
    angle: 5.0
    scale: 0.25
  - center_x: 0.56
    center_y: 0.45
    angle: 30.0
    scale: 0.15
