name: Who Killed Hannibal?
source: https://knowyourmeme.com/memes/who-killed-hannibal
text:
  - style: default
    color: white
    font: thick
    anchor_x: 0.1
    anchor_y: 0.3
    angle: 0.0
    scale_x: 0.3
    scale_y: 0.1
    align: center
    start: 0.0
    stop: 1.0
  - style: default
    color: white
    font: thick
    anchor_x: 0.53
    anchor_y: 0.35
    angle: 0.0
    scale_x: 0.3
    scale_y: 0.1
    align: center
    start: 0.0
    stop: 1.0
  - style: default
    color: khaki
    font: thick
    anchor_x: 0.0
    anchor_y: 0.875
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.125
    align: center
    start: 0.2
    stop: 1.0
example:
  - Twin Towers
  - George Bush
  - Why would Al-Qaeda do this?
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
