name: Gru's Plan
source: https://knowyourmeme.com/memes/grus-plan
text:
  - style: default
    color: black
    font: thin
    anchor_x: 0.275
    anchor_y: 0.2
    angle: 0.0
    scale_x: 0.2075
    scale_y: 0.2
    start: 0.1
    stop: 1.0
  - style: default
    color: black
    font: thin
    anchor_x: 0.78
    anchor_y: 0.2
    angle: 0.0
    scale_x: 0.205
    scale_y: 0.2
    start: 0.3
    stop: 1.0
  - style: default
    color: black
    font: thin
    anchor_x: 0.28
    anchor_y: 0.7
    angle: 0.0
    scale_x: 0.205
    scale_y: 0.2
    start: 0.5
    stop: 1.0
  - style: default
    color: black
    font: thin
    anchor_x: 0.78
    anchor_y: 0.7
    angle: 0.0
    scale_x: 0.205
    scale_y: 0.2
    start: 0.7
    stop: 1.0
example:
  - Learn how to make memes.
  - Make a meme.
  - No one likes it.
  - No one likes it.
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
