name: Drowning High Five
source: https://knowyourmeme.com/memes/drowning-high-five
text:
  - style: default
    color: white
    font: thick
    anchor_x: 0.03
    anchor_y: 0.33
    angle: 0.0
    scale_x: 0.46
    scale_y: 0.15
  - style: default
    color: white
    font: thick
    anchor_x: 0.51
    anchor_y: 0.14
    angle: 0.0
    scale_x: 0.2
    scale_y: 0.2
  - style: default
    color: khaki
    font: thick
    anchor_x: 0.03
    anchor_y: 0.82
    angle: 0.0
    scale_x: 0.46
    scale_y: 0.15
example:
  - Me Asking for Help
  - Online Commenter
  - I'm having that problem too.
overlay:
  - center_x: 0.585
    center_y: 0.14
    scale: 0.2
