name: See? Nobody Cares
source: http://knowyourmeme.com/memes/see-nobody-cares
text:
  - color: white
    style: upper
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
  - color: white
    style: upper
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
styles:
  -
sample:
  - WEâ€™VE GOT DODGSON HERE!
  - SEE? NOBODY CARES
