name: Always Has Been
source: https://knowyourmeme.com/memes/wait-its-all-ohio-always-has-been
text:
  - style: default
    color: white
    font: thin
    anchor_x: 0.45
    anchor_y: 0.35
    angle: 0.0
    scale_x: 0.25
    scale_y: 0.1
    align: center
    start: 0.0
    stop: 1.0
  - style: default
    color: white
    font: thin
    anchor_x: 0.75
    anchor_y: 0.0
    angle: 0.0
    scale_x: 0.25
    scale_y: 0.1
    align: center
    start: 0.0
    stop: 1.0
  - style: default
    color: white
    font: thick
    anchor_x: 0.375
    anchor_y: 0.8
    angle: 0.0
    scale_x: 0.25
    scale_y: 0.1
    align: center
    start: 0.0
    stop: 1.0
  - style: default
    color: white
    font: thick
    anchor_x: 0.75
    anchor_y: 0.7
    angle: 0.0
    scale_x: 0.25
    scale_y: 0.1
    align: center
    start: 0.0
    stop: 1.0
example:
  - Wait, it's round?
  - Always has been
  - Flat Earther
  - Science
overlay:
  - center_x: 0.27
    center_y: 0.47
    angle: 0.0
    scale: 0.425
