name: Distracted Boyfriend
source: https://knowyourmeme.com/memes/distracted-boyfriend
text:
  - style: default
    color: white
    font: thick
    anchor_x: 0.12
    anchor_y: 0.7
    angle: 0.0
    scale_x: 0.325
    scale_y: 0.1
    align: center
    start: 0.0
    stop: 1.0
  - style: default
    color: white
    font: thick
    anchor_x: 0.55
    anchor_y: 0.45
    angle: 0.0
    scale_x: 0.175
    scale_y: 0.1
    align: center
    start: 0.0
    stop: 1.0
  - style: default
    color: white
    font: thick
    anchor_x: 0.74
    anchor_y: 0.66
    angle: 0.0
    scale_x: 0.2
    scale_y: 0.1
    align: center
    start: 0.0
    stop: 1.0
example:
  - Socialism
  - The Youth
  - Capitalism
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
