name: I'm Going to Build My Own Theme Park
source: http://knowyourmeme.com/memes/im-going-to-build-my-own-theme-park-with-blackjack-and-hookers
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
  - style: upper
    color: white
    font: thick
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
example:
  - i'm going to build my own theme park
  - with blackjack and hookers
overlay:
  - center_x: 0.5
    center_y: 0.5
    scale: 0.25
