name: Phoebe Teaching Joey
source: https://knowyourmeme.com/photos/1846826-phoebe-teaching-joey
text:
  - style: default
    color: white
    font: thick
    anchor_x: 0.0
    anchor_y: 0.175
    angle: 0.0
    scale_x: 0.5
    scale_y: 0.05
  - style: default
    color: white
    font: thick
    anchor_x: 0.5
    anchor_y: 0.175
    angle: 0.0
    scale_x: 0.5
    scale_y: 0.05
  - style: none
    color: white
    font: thick
    anchor_x: 0.0
    anchor_y: 0.425
    angle: 0.0
    scale_x: 0.5
    scale_y: 0.05
  - style: none
    color: white
    font: thick
    anchor_x: 0.5
    anchor_y: 0.425
    angle: 0.0
    scale_x: 0.5
    scale_y: 0.05
  - style: none
    color: white
    font: thick
    anchor_x: 0.0
    anchor_y: 0.675
    angle: 0.0
    scale_x: 0.5
    scale_y: 0.05
  - style: none
    color: white
    font: thick
    anchor_x: 0.5
    anchor_y: 0.675
    angle: 0.0
    scale_x: 0.5
    scale_y: 0.05
  - style: default
    color: white
    font: thick
    anchor_x: 0.0
    anchor_y: 0.925
    angle: 0.0
    scale_x: 0.5
    scale_y: 0.05
  - style: default
    color: white
    font: thick
    anchor_x: 0.5
    anchor_y: 0.925
    angle: 0.0
    scale_x: 0.5
    scale_y: 0.05
example:
  - Cast it
  - Cast it
  - into
  - into
  - the fire
  - the fire
  - Cast it into the fire.
  - Keep the Ring of Power!
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
